FROM node:22-alpine AS frontend

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY resources ./resources
COPY vite.config.* ./
COPY public ./public

RUN npm run build


FROM nginx:1.27-alpine

WORKDIR /var/www/html

COPY --from=frontend /app/public /var/www/html/public
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf